version: '3.7'
x-django: &django
  volumes:
  - ./src/project/settings/local.py:/code/src/project/settings/local.py
services:
  nginx:
    ports:
      - ${VISU_PORT:-80}:80
  cron:
    <<: [ *django ]
  django:
    <<: [ *django ]
    ports:
    - "8000:8000"
